### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by aronwk-aaron** [I-Am-Dench/nimbus-launcher#18]
just an fyi for linux stuff, would recommend requiring `proton`
here is a command that I use:
`WINEDLLOVERRIDES="dinput8.dll=n,b" PROTON_USE_WINED3D=1 proton legouniverse`
using a modloader that injects via dinput8.dll

**Comment by I-Am-Dench** [comment]
Thanks! Been looking for something like this. Will implement and test it when I get the chance.
