### ISSUE TITLE
boot.cfg parsing should allow for a comma or newline delimiter

### ISSUE THREAD

**Issue by EmosewaMC** [I-Am-Dench/nimbus-launcher#20]
https://github.com/I-Am-Dench/nimbus-launcher/blob/d66a97951a0173b31bec97366a80726e11d2068d/ldf/unmarshal.go#L95C14-L95C21

i assume this is the parser for ldf keys, the live client parses the boot.cfg on a comma or a newline (\n) delimiter and not just a comma.  It may be worth considering making this app able to do both as well so manually edited cfg files that just use the new-line delimiter dont have failed to parse values 👍 

I didnt say it in any of my issues, but awesome patcher.  nice to see some external work towards LU once-in-a-while

**Comment by I-Am-Dench** [comment]
Seems like a quick fix. Will update soon.

And thanks for checking out the launcher! I've been following Darkflame Universe since before the server code was released and you guys are awesome! So glad to finally experience the game again
